name: Build Libra Image and Save as Tar

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Prepare output
        run: mkdir -p output

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          DOCKER_BUILDKIT=1 docker build -t myorg/libra:${IMAGE_TAG} .

      - name: Save image as TAR
        run: |
          IMAGE_TAG=${{ github.sha }}
          TAR_PATH="output/libra-${IMAGE_TAG}.tar"
          docker save myorg/libra:${IMAGE_TAG} -o "$TAR_PATH"

      - name: Upload TAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: libra-tar
          path: output/
